[package]
version = "0.0.0" # This version will be automatically updated
readme = "README.md"
name = "pedersen"
edition = "2021"
repository = "https://github.com/spaceandtimelabs/pedersen"
authors = [
    "Joe <joseribeiro1017@gmail.com>",
    "Ryan Burn <ryan@spaceandtime.io>"
]
keywords = ["gpu-cryptography", "gpu-crypto", "gpu-ristretto", "gpu-curve25519", "gpu-ristretto255"]
description = "A GPU implementation of group operations on ristretto255 and Curve25519"
exclude = [
    "**/.gitignore",
    ".gitignore"
]

[dependencies]
byte-slice-cast = {version = "1.2"}
curve25519-dalek = { version = "3" }
proofs_gpu = {version = "6.4", registry = "proofs_gpu_reg"}

# this sections is shared by tests, benchmarks, and examples
[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"]}
rand_core = "0.5"
rand = "0.7"

[[bench]]
name = "pedersen_benchmarks"
harness = false

[features]
default = ["pip-cpu"]
pip-cpu = []
naive-cpu = []
naive-gpu = []
