[package]
version = "0.0.0" # This version will be automatically updated
readme = "README.md"
name = "proofs-gpu"
edition = "2021"
repository = "https://github.com/spaceandtimelabs/proofs-gpu-rust"
keywords = ["gpu-cryptography", "gpu-crypto", "gpu-ristretto", "gpu-curve25519", "gpu-ristretto255"]
description = "High-Level Rust wrapper for the proofs-gpu sys crate "
exclude = [
    "**/.gitignore",
    ".gitignore"
]

[dependencies]
byte-slice-cast = { version = "1.2" }
curve25519-dalek = { version = "3", features = ["serde"] }
merlin = "2"
proofs-gpu-sys = { version = "10.0" }
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"

# this sections is shared by tests, benchmarks, and examples
[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
rand = "0.7"
rand_core = "0.5"

[[bench]]
harness = false
name = "proofs_gpu_benchmarks"

[features]
cpu = []
default = ["gpu"]
gpu = []
