[package]
name = "pedersen"
version = "0.0.0" # This version will be automatically updated
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-slice-cast = "1.2.1"
curve25519-dalek = "3.2.1"

[dependencies.proofs_gpu]
path = "proofs-gpu-sys/"

# this sections is shared by tests, benchmarks, and examples
[dev-dependencies]
criterion = "0.3"
rand_core = "0.5"

[[bench]]
name = "pedersen_benchmarks"
harness = false

[features]
default = ["gpu"]
cpu = []
gpu = []
