[package]
version = "0.0.0" # This version will be automatically updated
readme = "README.md"
name = "proofs-gpu"
edition = "2021"
repository = "https://github.com/spaceandtimelabs/proofs-gpu-rust"
keywords = ["gpu-cryptography", "gpu-crypto", "gpu-ristretto", "gpu-curve25519", "gpu-ristretto255"]
description = "High-Level Rust wrapper for the proofs-gpu sys crate "
exclude = [
    "**/.gitignore",
    ".gitignore"
]

[dependencies]
byte-slice-cast = {version = "1.2"}
curve25519-dalek = { version = "3", features = ["serde"] }
merlin = "2"
thiserror = "1"
serde = { version = "1", features = ["serde_derive"] }
proofs-gpu-sys = { version = "8.2" }

# this sections is shared by tests, benchmarks, and examples
[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"]}
rand_core = "0.5"
rand = "0.7"

[[bench]]
name = "proofs_gpu_benchmarks"
harness = false

[features]
default = ["gpu"]
cpu = []
gpu = []
