[package]
name = "pedersen"
version = "0.0.0" # This version will be automatically updated
edition = "2021"

[dependencies]
byte-slice-cast = {version = "1.2.1"}
curve25519-dalek = {version = "3.2.1"}
proofs_gpu = {version = "2.0.1", registry = "proofs_gpu_reg"}

# this sections is shared by tests, benchmarks, and examples
[dev-dependencies]
criterion = "0.3"
rand_core = "0.5"

[[bench]]
name = "pedersen_benchmarks"
harness = false

[features]
default = ["gpu"]
cpu = []
gpu = []
